trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    # Read current version
    VERSION=$(cat version.txt)
    echo "Current version: $VERSION"

    # Split version into parts
    IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

    # Bump patch version
    PATCH=$((PATCH + 1))

    # Create new version
    NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
    echo "New version: $NEW_VERSION"
    echo "$NEW_VERSION" > version.txt

    # Configure Git
    git config user.email "devops@example.com"
    git config user.name "Azure DevOps"

    # Commit and push new version
    git add version.txt
    git commit -m "chore: bump to v${NEW_VERSION}"
    git push origin main

    # Tag the new version
    git tag "v${NEW_VERSION}"
    git push origin "v${NEW_VERSION}"
  displayName: 'Bump Version and Tag'
